name: Linux release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Install packages
      run: |
        sudo apt-get install libgirepository1.0-dev
    - uses: actions/checkout@v2
    - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit==2.13.0
        pip install -r requirements.txt
    - name: Run pyinstaller
        run: |
            pyinstaller --add-data src/style.css:. -n butter src/__main__.py --distpath dist/butter/
    - name: Create archive
        run: |
            tar -cf dist/butter-${{ env.RELEASE_VERSION }}.tar.gz dist/butter/
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/butter-${{ env.RELEASE_VERSION }}.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
